CREATE TABLE db_active(
    id INTEGER PRIMARY KEY AUTOINCREMENT, 
    db_status TINYINT NOT NULL, 
    created_tms TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP 
)


CREATE TABLE binlog_files(
    id INTEGER PRIMARY KEY AUTOINCREMENT, 
    file_name VARCHAR(100) NOT NULL, 
    created_tms TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)