CREATE TABLE IF NOT EXISTS users(
    id INTEGER PRIMARY KEY AUTOINCREMENT, 
    user_uuid VARCHAR(36) NOT NULL UNIQUE, 
    name VARCHAR(100) NOT NULL, 
    username VARCHAR(25) NOT NULL UNIQUE, 
    email VARCHAR(50) NOT NULL UNIQUE, 
    password VARCHAR(50) NOT NULL, 
    created_tms TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
    updated_tms TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)
